config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'dashboard#show', as: :root
    resources :kiosks do
      resources :slides
    end

    get 'session' => 'sessions#new', as: :sign_in
    post 'session' => 'sessions#create'
    delete 'session' => 'sessions#delete', as: :sign_out
  end

  get "/:id" => 'kiosks#show', as: :kiosk

  root 'kiosks#show'

end

app/models/kiosk.rb
class Kiosk < ActiveRecord::Base
  has_many :slides
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :kiosk
  scope :active, -> { where("start_date <= ?", Date.today).where("end_date >= ?", Date.today) }
  scope :ordered, -> { order(order_number: :asc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, uniqueness: true, presence: true
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  layout 'admin'
  
  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.nil?
      redirect_to admin_sign_in_path, notice: "Please Sign in"
      return false
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController

  before_action :authenticate_user!

  def show
  end
end

app/controllers/admin/kiosks_controller.rb
class Admin::KiosksController < Admin::AdminController

  before_action :authenticate_user!

  def index
    @kiosks = Kiosk.all
  end

  def show
    @kiosk = Kiosk.find params[:id]
  end

  def new
    @kiosk = Kiosk.new
  end

  def create
    @kiosk = Kiosk.new params.require(:kiosk).permit(:name)
    if @kiosk.save
      redirect_to [:admin, @kiosk], notice: "Created!"
    else
      render :new
    end
  end

  def edit
    @kiosk = Kiosk.find params[:id]
  end

  def update
    @kiosk = Kiosk.find params[:id]
    if @kiosk.update params.require(:kiosk).permit(:name)
      redirect_to [:admin, @kiosk], notice: "Updated!"
    else
      render :edit
    end
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::AdminController
  def new
  end

  def create
    @current_user = User.where("username ILIKE ?", params[:username]).first
    if @current_user.try :authenticate, params[:password]
      session[:user_id] = @current_user.id
      redirect_to admin_root_path, notice: "Signed in!"
    else
      flash.now[:alert] = "Something was wrong with your username and/or password"
      render :new
    end
  end

  def delete
    session.delete(:user_id)
    redirect_to admin_root_path, notice: "signed out!"
  end
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < Admin::AdminController

  before_action :authenticate_user!

  before_action do
    @kiosk = Kiosk.find params[:kiosk_id]
  end

  def index
    @slides = @kiosk.slides.all
  end

  def show
    @slide = @kiosk.slides.find params[:id]
  end

  def new
    @slide = @kiosk.slides.build
    @slide.end_date = 2.years.from_now
  end

  def create
    @slide = @kiosk.slides.build slide_params
    if @slide.save
      redirect_to [:admin, @kiosk, :slides], notice: "Created!"
    else
      render :new
    end
  end

  def edit
    @slide = @kiosk.slides.find params[:id]
  end

  def update
    @slide = @kiosk.slides.find params[:id]
    if @slide.update slide_params
      redirect_to [:admin, @kiosk, :slides], notice: "Updated!"
    else
      render :edit
    end
  end

  def destroy
    @slide = @kiosk.slides.find params[:id]
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to [:admin, @kiosk, :slides], notice: "Destroyed!" }
    end
  end

  private

  def slide_params
    params.require(:slide).permit(:order_number, :start_date, :end_date, :markdown_content, :pattern)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kiosks_controller.rb
class KiosksController < ApplicationController


  def index
    @kiosks = Kiosk.all
  end
  def show
    @kiosk = Kiosk.last
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/kiosks_helper.rb
module Admin::KiosksHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
require 'open-uri'
require 'json'
require 'ostruct'

module ApplicationHelper

  def comic_url
    url = 'http://www.commitstrip.com/en/'
    agent = Mechanize.new
    page = agent.get(url)

    detail_page = agent.click page.at(".excerpts .excerpt a")
    detail_page.at(".entry-content img")['src']
  end

  def fetch_speakers
    json = open("https://tiyspeakers.herokuapp.com/api/talks").read
    JSON.parse(json, object_class: OpenStruct)
  end


  def all_speakers
    @all_speakers ||= fetch_speakers
  end

  def this_weeks_speakers

    all_speakers.select do |t|
      talk_date = t["date"] || Date.parse("3000-02-02").to_date.strftime('%m/%d/%Y')
      talk_date >= Time.now.beginning_of_week(start_day = :sunday) && Time.now.end_of_week(end_day = :saturday) >= talk_date
    end.sort_by {|date| date.date}
  end

  def fetch_meetups
      json = open("https://api.meetup.com/2/events?&sign=true&photo-host=public&venue_id=23753432&page=20&key=326e493f58383976434f5963243a5e&callback=?").read
      JSON.parse(json, object_class: OpenStruct)["results"]
  end

  def all_meetups
    @all_meetups ||= fetch_meetups
  end

  def meetups_this_week
    all_meetups.select {|t| t["time"] >= Time.now.beginning_of_week(start_day = :sunday).to_i*1000 && Time.now.end_of_week(end_day = :saturday).to_i*1000 >= t["time"] }
  end

  def fetch_meetups_worth_going
    json = open("https://api.meetup.com/2/events?member_id=100501792&offset=0&format=json&limited_events=False&photo-host=public&page=20&fields=&order=time&desc=false&status=upcoming&sig_id=100501792&sig=a16f1f16f21e97938877eb5d4bb2a1399739a0bb").read
    JSON.parse(json, object_class: OpenStruct)["results"]
  end

  def all_meetups_worth_going
    @meetups_worth ||= fetch_meetups_worth_going
  end

  def meetups_worth_this_week
    all_meetups_worth_going.select {|t| t["time"] >= Time.now.beginning_of_week(start_day = :sunday).to_i*1000 && Time.now.end_of_week(end_day = :sunday).to_i*1000 >= t["time"] }
  end

  def fetch_announcements
    json = open("https://tiyspeakers.herokuapp.com/api/v1/announcements").read
    JSON.parse(json, object_class: OpenStruct)["announcements"]
  end

  def all_announcements
    @all_announcements ||= fetch_announcements
  end

  def this_week_announcements
    all_announcements.select {|t| t["date"] >= Time.now.beginning_of_week(start_day = :sunday) && Time.now.end_of_week(end_day = :saturday) >= t["date"] }
  end

  def fetch_fun_facts
      json = open("https://tiyfunfactz.herokuapp.com/students.json").read
      JSON.parse(json, object_class: OpenStruct)["students"]
  end

  def all_fun_facts
    @all_fun_facts ||= fetch_fun_facts
  end

  def sample_fun_facts
    all_fun_facts.sample(5)
  end

  def fetch_all_demos
    json = open("https://tiydemoday.herokuapp.com/api/v1/students").read
    JSON.parse(json, object_class: OpenStruct)["students"]
  end

  def all_demos
    @all_demos ||= fetch_all_demos
  end

  def demo
    all_demos.select {|t| t["cohort_id"] == 21 }.sort_by {|lastname| lastname["name"].split(" ").last}
  end


end

app/views/admin/dashboard/show.html.erb
<h1>Admin Dashboard</h1>

<div class="list-group">
  <%= link_to 'Manage Kiosks', admin_kiosks_path, class: "list-group-item" %>
  <%= link_to 'Manage Users', "#", class: "list-group-item" %>
</div>

app/views/admin/kiosks/edit.html.erb
<h1>Admin Kiosks</h1>

<%= simple_form_for [:admin, @kiosk] do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/admin/kiosks/index.html.erb
<div class="page-header">
  <h1>Kiosks</h1>
</div>

<div class="well">
  <p class="text-right">
    <%= link_to 'New Kiosk', new_admin_kiosk_path, class: "btn btn-primary" %>
  </p>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        URL
      </th>
      <th>
        Edit
      </th>
      <th>
        Slides
      </th>
    </tr>
  </thead>
  <tbody>
    <% if @kiosks.empty? %>
      <td colspan="3">
        No Kiosks found
      </td>
    <% else %>
      <% @kiosks.each do |kiosk| %>
        <tr>
          <td>
            <%= link_to kiosk.name, [:admin, kiosk] %>
          </td>
          <td>
            <%= link_to kiosk_url(kiosk), kiosk_url(kiosk) %>

          </td>
          <td>
            <%= link_to 'Edit', edit_admin_kiosk_path(kiosk) %>
          </td>
          <td>
            <%= link_to "Slides (#{kiosk.slides.active.count})", admin_kiosk_slides_path(kiosk) %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/kiosks/new.html.erb
<h1>Admin Kiosks</h1>

<%= simple_form_for [:admin, @kiosk] do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/admin/kiosks/show.html.erb
<h1><%= @kiosk.name %></h1>

<%= link_to 'Manage Slides', [:admin, @kiosk, :slides ], class: "btn btn-block btn-lg btn-primary" %>

<dl class="">
  <dt>Slides</dt>
  <dd><%= @kiosk.slides.active.count %></dd>
  <dt>URL</dt>
  <dd>
            <%= link_to kiosk_url(@kiosk), kiosk_url(@kiosk) %>
  </dd>
</dl>

app/views/admin/slides/edit.html.erb
<div class="page-title">
  <h1>Editing Slide</h1>
</div>

<%= simple_form_for [:admin, @kiosk, @slide] do |f| %>
  <%= f.input :pattern, collection: %w(markdown today announcements meetups_at_tiy meetups_worth_this_week this_week_speaker comic about grill iron_pints wifi fun_facts demo _welcome_to_demo) %>
  <%= f.input :order_number, collection: (1..100) %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :markdown_content, as: :text, input_html: {rows: 10} %>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/admin/slides/index.html.erb
<div class="page-header">
  <h1>Slides <small><%= link_to 'Return to Kiosk', [:admin, @kiosk] %></small></h1>
</div>

<div class="well">
  <p class="text-right">
    <%= link_to 'New Slide', new_admin_kiosk_slide_path(@kiosk), class: "btn btn-primary" %>
  </p>
</div>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>
        Order
      </th>
      <th>
        Pattern
      </th>
      <th>
        Action
      </th>
    </tr>
  </thead>
  <tbody>
    <% if @slides.empty? %>
      <td colspan="3">
        No Slides found
      </td>
    <% else %>
      <% @slides.ordered.each do |slide| %>
        <tr>
          <td>
            <%= slide.order_number %>
          </td>
          <td>
            <%= slide.pattern %>
          </td>
          <td>
            <%= link_to 'Edit', edit_admin_kiosk_slide_path(@kiosk, slide), class: "btn btn-primary" %> <%= link_to "Delete", admin_kiosk_slide_path(@kiosk, slide), :method => :delete, :confirm => "Are you sure?", class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/slides/new.html.erb
<div class="page-title">
  <h1>New Slide</h1>
</div>

<%= simple_form_for [:admin, @kiosk, @slide] do |f| %>
  <%= f.input :pattern, collection: %w(markdown today announcements meetups_at_tiy meetups_worth_this_week this_week_speaker comic about grill iron_pints wifi fun_facts demo welcome_to_demo_day) %>
  <%= f.input :order_number, collection: (1..100) %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :markdown_content, as: :text, input_html: {rows: 10} %>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/kiosks/_about.html.erb
<section>
  <section>
    <h2>About The Iron Yard</h2>
    <p>
      The Iron Yard exists to create real, lasting change for people, companies and communities through technology education.
    </p>
    <br>
    <p>
      Our educational resources provide a solution at the juncture of supply, demand, business and a broken education system. We are committed to training the highest-quality technology professionals in the world, both in skill and in character.
    </p>
  </section>

  <section>
    <h2>About The Courses</h2>
  </section>

  <!-- <section>
    <h3>Back End Engineering - C# and .NET</h3>
    <p>
      <%= image_tag "https://www.theironyard.com/content/dam/theironyard/icons/icon-BackEnd-update.png" %>
    </p>
    <p>
      Back End Engineering focuses on the logic and database needs required to run and scale web applications. Back End products combine databases, APIs, and user interface frameworks. Backend developers deploy fully formed products to the cloud, integrate with online services, and enable mobile and front end applications.
    </p>

  </section> -->

  <section>
    <h3>Web Development Career Path</h3>
    <p>
      <%= image_tag "https://www.theironyard.com/content/dam/theironyard/icons/icon-FrontEnd-update.png" %>
    </p>
    <p>
      Front End Engineering focuses on creating experiences in web browsers that users see and interact with. The discipline covers a broad area, from web design principles to complex JavaScript applications that manage data. The tools used in Front End Engineering are ubiquitous—no matter the technology used on the Back End, Front-Enders are responsible for delivering the experience and data to the person using the web application.
    </p>
  </section>

  <!-- <section>
    <h3>Mobile Engineering</h3>
    <p>
      <%= image_tag "https://www.theironyard.com/content/dam/theironyard/icons/icon-Mobile-update.png" %>
    </p>
    <p>
      Mobile Engineering focuses on creating native experiences designed specifically for mobile operating systems and the hardware they run on. Mobile developers create tactile apps that leverage internet connectivity, content capture functionality and hardware-specific features. End users download and use those apps to consume, create and distribute using their devices wherever they are.
    </p>
  </section> -->

  <section>
    <h5>Learn Even More at:</h5>
    <h3>
      theironyard.com
    </h3>
  </section>
</section>

app/views/kiosks/_announcements.html.erb
<section>
    <h3>Announcements</h3>
    <table>
      <% this_week_announcements.each do |announcement| %>
        <tr>
          <td>
            <h4><%= Date.parse(announcement.date).strftime('%a, %b %d').to_s %></h4>
          </td>
          <td>
            <h4><%= announcement.info %></h4>
          </td>
        </tr>
      <% end %>
    </table>
</section>

app/views/kiosks/_comic.html.erb
<section>
  <%= image_tag comic_url, class: "rounded" %>
</section>

app/views/kiosks/_fun_facts.html.erb
<% all_fun_facts.each do |ff| %>
  <section>
    <h3>Fun Facts About</h3>
    <h3> <%= ff.name.titleize %> </h3>
    <h4><%= ff.cohort.name %></h4>
     <%= image_tag("https://tiyfunfactz.herokuapp.com#{ff.profile_image}", :class => "circle") %>
     <h4> "<%= ff.fun_fact %>"</h4>

  </section>
<% end %>

app/views/kiosks/_grill.html.erb
<section>
  <h3>Half Way Celebration</h3>
  <h4>This Friday marks the official halfway point of the class.  Let's celebrate with grilled meats and veggies!</h4>
  <p>
    <%= image_tag "grill.gif", :class => "rounded" %>
  </p>

</section>

app/views/kiosks/_iron_pints.html.erb
<section>
  <h3>Join Us for Iron Social</h3>
  <%= image_tag "iron_pints.png", height: '400', width: '400' %>
  <h3>Fridays from 3-4pm!</h3>
</section>

app/views/kiosks/_markdown.html.erb
<section data-markdown>
<%= slide.markdown_content %>
</section>

app/views/kiosks/_meetups_at_tiy.erb
<% unless meetups_this_week.empty? %>
  <section>
  <h3>Meetups @TIY This Week</h3>
    <ul>
      <% meetups_this_week.each do |meetup| %>
        <li><h4><%= meetup.group.name %> - <%= Time.at(meetup.time/1000).strftime('%a, %b %d - %l:%M%p') %> - <em>"<%= meetup.name %>"</em></h4></li>
      <% end %>
    </ul>
    </section>
<% end %>

app/views/kiosks/_meetups_worth_this_week.html.erb
<br>
<% meetups_worth_this_week.each do |meetup| %>
<section>
  <h3>Tech Meetups This Week</h3>
  <em>"<%= meetup.name %>"</em>
  <br>
  <br>
  <h4><%= meetup.group.name %></h4>
  <h5><%= Time.at(meetup.time/1000).strftime('%a, %b %d - %l:%M%p') %> @ <% if meetup.venue.nil? %> <%= "TBD" %> <% else %> <%= meetup.venue.name %><% end %></h5>
  <br>
</section>

<% end %>

app/views/kiosks/_this_week_speaker.html.erb
<% this_weeks_speakers.each do |speaker| %>
  <section>
    <h3>Guest Speaker</h3>
    <h3> <%= speaker.date %> </h3>
    <h3> <%= speaker.name %>  </h3>
    <h3> <%= speaker.company %>  </h3>
   <%= image_tag(speaker.pic, :class => "circle") %>
  </section>
<% end %>

app/views/kiosks/_today.html.erb
<section>
  <h2><%= Date.today.strftime "%A, %B %d" %></h2>
  <%= image_tag "logo_big.png" %>
</section>

app/views/kiosks/_welcome_to_demo.html.erb
<section>
  <h2>Welcome to Demo Day!</h2>
  <%= image_tag "logo_big.png" %>
</section>

app/views/kiosks/_wifi.html.erb
<section>
  <%= image_tag "wifi.png", :class => "rounded" %>
</section>

app/views/kiosks/show.html.erb
<div class="reveal">
  <div class="slides">
    <% @kiosk.slides.active.ordered.each do |slide| %>
      <%= render partial: slide.pattern, locals: {slide: slide} %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="flash">
  <% if notice %>
    <div class="alert alert-info">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger">
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TiyKioskAdmin</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'layouts/flash' %>

  <header>
    <ul>
      <li><%= link_to 'Admin Root', admin_root_path %></li>
      <li><%= link_to 'Admin Kiosks', admin_root_path %></li>
      <li><%= link_to 'Sign Out', admin_sign_out_path, method: :delete %></li>
    </ul>
  </header>




  <div class="container">
    <%= yield %>
  </div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TiyKioskAdmin</title>

  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">

  <!-- Use title if it's in the page YAML frontmatter -->
  <title>TIY Houston Announcements</title>

  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic|Ubuntu+Mono:400,700,400italic,700italic|Alegreya:400italic,700italic,400,700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>